//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theCapitol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leader
    {
        public int LeaderId { get; set; }
        public int ConnectionId { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ProfilePic { get; set; }
        public string Notes { get; set; }
        public bool IsStudentLeader { get; set; }
    
        public virtual Connection Connection { get; set; }
    }
}
